# NumPy
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

* NumPy’s main object is the homogeneous multidimensional array.
* It is a table of elements (usually numbers),  
   * all of the same type, 
   * indexed by a tuple of positive integers. 
* In NumPy dimensions are called axes. The number of axes is rank.1

### Functions and Methods Overview
https://docs.scipy.org/doc/numpy-dev/reference/routines.html#routines
Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.

Array Creation    
    arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like    
Conversions
    ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
Manipulations
    array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
Questions
    all, any, nonzero, where
Ordering
    argmax, argmin, argsort, max, min, ptp, searchsorted, sort
Operations
    choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
Basic Statistics
    cov, mean, std, var
Basic Linear Algebra
    cross, dot, outer, linalg.svd, vdot 
    
### Basic Functions


** ndarray.ndim  **   
    the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.    
** ndarray.shape **     
    the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.   
** ndarray.size **     
    the total number of elements of the array. This is equal to the product of the elements of shape.   
** ndarray.dtype **   
    an object describing t provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.   
** ndarray.itemsize**    
    the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It i*
    the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities. 

***

### Writing Codes:    
To write any NumPy code, we need to import the package first:


In [1]:
# import the NumPy package first
import numpy as np

### Creating Arrays:
Creating Arrays can be many ways-
#### 1D Array

In [7]:
# 1D array
a = np.array([1,2,3.3,9,8]) # not like other languages array(1,2,3.3,9,8)

In [8]:
a = np.array([1,2,3,4])  # for integer

In [9]:
a

array([1, 2, 3, 4])

***
#### Multi Dimentional Array
Array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [11]:
b = np.array([(1.5,2,3), (4,5,6)])

In [12]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [4]:
# creating array with datatype
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

#### Creating Array from Built in functions
*The default datatype will be in folat *

In [5]:
# zeros: Returns arry with zeros of 0 values; default dtype is 
np.zeros( (2,3) )

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
# ones: Returns array with ones
np.ones( (2,3,4), dtype=np.int16 ) # 2= 2D; (3,4)=3x4 matrix

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [11]:
# empty:  Return a new uninitialized array
np.empty( (2,3) )                                 # uninitialized, output may vary; (2,3)=2x3

array([[  6.91937893e-310,   4.64827434e-310,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000]])

In [27]:
import numpy as np

In [23]:
data= np.arange(0,100,2).reshape(5,10)


In [25]:
data.argsort(axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])


Operations

    choose,
    compress,
    cumprod,
    cumsum,
    inner,
    ndarray.fill,
    imag,
    prod,
    put,
    putmask,
    real,
    sum



In [38]:
# cumprod
# it is a cumulative product of an array
data1=np.random.randint(1,10,size=10)


In [39]:
data1

array([3, 9, 5, 4, 5, 5, 9, 9, 8, 4])

In [40]:
np.cumprod(data1) # the last number is the final number

array([       3,       27,      135,      540,     2700,    13500,
         121500,  1093500,  8748000, 34992000])

In [44]:
data2=np.array([1,2,3])

In [45]:
np.cumprod(data2) # the last number is the final number

array([1, 2, 6])

In [54]:
data3=np.random.randint(1,11,size=(2,5))


In [57]:
data3

array([[9, 9, 2, 8, 5],
       [1, 8, 1, 2, 4]])

In [59]:
np.cumprod(data3,axis=1)

array([[   9,   81,  162, 1296, 6480],
       [   1,    8,    8,   16,   64]])

In [61]:
# cumsum
np.cumsum(data1)

array([ 3, 12, 17, 21, 26, 31, 40, 49, 57, 61])

In [62]:
data1

array([3, 9, 5, 4, 5, 5, 9, 9, 8, 4])

In [65]:
#inner; a[:]* b[:]=a[0]*b[0]+a[1]*b[1]+...+a[n]*b[n]
a = np.array([1,2,3])
b = np.array([1,1,0])

In [66]:
 np.inner(a, b)

3

In [67]:
a = np.arange(24).reshape((2,3,4))


In [68]:
b = np.arange(4)


In [69]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [70]:
b

array([0, 1, 2, 3])

In [71]:
 np.inner(a, b)

array([[ 14,  38,  62],
       [ 86, 110, 134]])

In [72]:
#imag ;Return the imaginary part of the elements of the array.

In [77]:
 a = np.array([1+2j, 3+4j, 5+6j])

In [83]:
a

array([ 1.+2.j,  3.+4.j,  5.+6.j])

In [82]:
np.imag(a)

array([ 2.,  4.,  6.])

In [84]:
a.dtype

dtype('complex128')

In [89]:
# prod;  data1
#ac=np.array([122322222222,24444444444444,355555555555])
x = np.array([536870910, 536870910, 536870910, 536870910])
np.prod(x)

6917529010461212688

##\ ----
---